### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ezekielgn** [PabloEGonz/JavaScriptCapstone-#21]
In this project, we are two partners: @enmanuelbayen (student B) & @PabloEGonz  (student A). 

Here is the link for the GitHub Project: https://github.com/PabloEGonz/JavaScriptCapstone-/projects/1

**Comment by tresorsawasawa** [comment]
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @PabloEGonz and @enmanuelbayen 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Good issue description :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] As required for the project, kindly make sure  all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
![Screenshot from 2023-05-22 18-51-00](https://github.com/PabloEGonz/JavaScriptCapstone-/assets/83042742/46edb543-4bed-46d4-b1ec-14a84d1cd4af)

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ghost** [comment]
Hi Team, 

You can go ahead with your project.
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/da75JuW2HHuBNqOHHE/giphy.gif"/>

## Highlights

✅ Cards are assigned properly


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
